[package]
name = "shadertoy"
version = "0.1.0"
authors = ["Guillaume Anthouard <guillaume.anthouard@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[dependencies]
# GPU API
wgpu = { version = "0.7" }
# Windowing
winit = { version = "0.24" }
# Async runtime
futures-executor = { version = "0.3" }
# To compile shaders to spir-v
shaderc = { version = "0.7" }
# Error types
anyhow = { version = "1" }
# Converting types to bytes
bytemuck = { version = "1", features = ["derive"] }
# Algebraic data types
ultraviolet = { version = "0.7", features = ["bytemuck", "int"] }
# File watcher
hotwatch = { version = "0.4" }
# logger api
log = { version = "0.4", features = ["std"] }
# Terminal UI
crossterm = { version = "0.18" }
tui = { version = "0.14", default-features = false, features = ["crossterm"] }
tui-logger = { version = "0.4", default-features = false, features = ["tui-crossterm"] }
