[package]
name = "nuance"
version = "0.2.0"
authors = ["Guillaume Anthouard <guillaume.anthouard@hotmail.fr>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]
description = "A tool to run your shaders on the gpu. Also a good demo application for wgpu-rs."
homepage = "https://github.com/Gui-Yom/nuance"
repository = "https://github.com/Gui-Yom/nuance"
license = "Apache-2.0"
readme = "README.md"
keywords = ["shaders", "glsl", "graphics", "visualization", "wgpu"]
categories = ["graphics", "rendering", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 4

[dependencies]
# GPU API
wgpu = "0.8"
# Windowing
winit = "0.24"
# Async runtime
futures-executor = "0.3"
# glsl to spirv
shaderc = "0.7"
# parse glsl
glsl-lang = "0.1"
# Error types
anyhow = "1"
# Math types
mint = "0.5"
# Converting types to bytes
crevice = { version = "0.6.0", path = "../crevice" }
# File watcher
notify = "4"
# File dialogs
rfd = "0.3"
# logger api
log = { version = "0.4", features = ["std"] }
simplelog = "0.10"
# GUI
egui = { version = "0.12" }#, git = "https://github.com/emilk/egui", rev = "29668b512888d3a8fe53da9258e7e6fcb2442610" }
egui_wgpu_backend = { version = "0.8" }#, git = "https://github.com/hasenbanck/egui_wgpu_backend", rev = "b651ee9b669fdce74f3e26356d61d5df78d80edf" }
egui_winit_platform = { version = "0.7", features = ["webbrowser"], path = "../egui_winit_platform" }
