[package]
name = "nuance"
version = "0.1.0"
authors = ["Guillaume Anthouard <guillaume.anthouard@hotmail.fr>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]
description = "A tool to run your shaders on the gpu. Also a good demo application for wgpu-rs."
homepage = "https://github.com/Gui-Yom/nuance"
repository = "https://github.com/Gui-Yom/nuance"
license = "Apache-2.0"
readme = "README.md"
keywords = ["shaders", "glsl", "graphics", "visualization", "wgpu"]
categories = ["graphics", "rendering", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 4

[dependencies]
# GPU API
wgpu = "0.7"
# Windowing
winit = "0.24"
# Async runtime
futures-executor = "0.3"
# glsl to spirv
shaderc = "0.7"
# parse glsl
glsl-lang = "0.1"
# Error types
anyhow = "1"
# Converting types to bytes
bytemuck = { version = "1", features = ["derive"] }
# File watcher
notify = "4"
# logger api
log = { version = "0.4", features = ["std"] }
simplelog = "0.10"
# GUI
egui = { version = "0.11" }#, git = "https://github.com/emilk/egui", rev = "035166276322b3f2324bd8b97ffcedc63fa8419f" }
egui_wgpu_backend = { version = "0.6" }
egui_winit_platform = "0.6"
