[package]
name = "shadertoy"
version = "0.1.0"
authors = ["Guillaume Anthouard <guillaume.anthouard@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[dependencies]
# GPU API
wgpu = { version = "0.6" }
# Windowing
winit = { version = "0.24" }
# Async runtime
futures-executor = { version = "0.3" }
# logger impl
pretty_env_logger = { version = "0.4" }
# logger api
log = { version = "0.4" }
# To compile shaders to spir-v
shaderc = { version = "0.7" }
# Error types
thiserror = { version = "1.0" }
# Converting types to bytes
bytemuck = { version = "1.4", features = ["derive"] }
# Algebraic data types
ultraviolet = { version = "0.7", features = ["bytemuck", "int"] }
# File watcher
hotwatch = { version = "0.4" }
