[package]
name = "nuance"
version = "0.1.0"
authors = ["Guillaume Anthouard <guillaume.anthouard@hotmail.fr>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 4

[dependencies]
# GPU API
wgpu = { version = "0.7" }
# Windowing
winit = { version = "0.24" }
# Async runtime
futures-executor = { version = "0.3" }
# glsl to spirv
shaderc = { version = "0.7" }
# parse glsl
glsl-lang = { git = "https://github.com/vtavernier/glsl-lang" }
# Error types
anyhow = { version = "1" }
# Converting types to bytes
bytemuck = { version = "1", features = ["derive"] }
# File watcher
notify = { version = "4.0" }
# logger api
log = { version = "0.4", features = ["std"] }
# Terminal UI
crossterm = { version = "0.18" }
tui = { version = "0.14", default-features = false, features = ["crossterm"] }
tui-logger = { version = "0.6" }
# GUI
egui = { version = "0.10" }
epi = { version = "0.10" }
egui_wgpu_backend = { version = "0.5" }
egui_winit_platform = { version = "0.5" }
chrono = { version = "0.4" }

[patch.crates-io]
lang-util = { git = "https://github.com/vtavernier/glsl-lang" }
lang-util-derive = { git = "https://github.com/vtavernier/glsl-lang" }
